# Generated by Django 5.2.7 on 2025-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('language', models.CharField(default='English', max_length=50)),
            ],
        ),
    ]
